import os 

# General
def delete_script_file(script_file_name):
    if os.path.exists(script_file_name):
        os.remove(script_file_name)

def write_cmd_to_script_file(script, script_file_name):
    delete_script_file(script_file_name)
    script_file_name = open(script_file_name, "a")
    for line in script:
        script_file_name.writelines(line+'\n')
    script_file_name.close()

# Custom 
def get_validate_vcf_md_script(vcf_json_py):
    markdown_script = []
    mdline = "# VCF 5.2 Configuration Validation"
    markdown_script.append(mdline)
    mdline = ("The following values were pulled from the vcf.json file that will be used during VCF Bringup.")
    markdown_script.append(mdline)
    mdline = ("")
    markdown_script.append(mdline)
    mdline = ("## General")
    markdown_script.append(mdline)
    mdline = ("| Parameter | Configured Value |")
    markdown_script.append(mdline)
    mdline = ("|-----------|------------------|")
    markdown_script.append(mdline)
    mdline = ("| dvSwitchVersion |  |")
    markdown_script.append(mdline)
    mdline = ("| skipEsxThumbprintValidation |  |")
    markdown_script.append(mdline)
    mdline = ("| managementPoolName |  |")
    markdown_script.append(mdline)
    mdline = ("| SDDC ID |  |")
    markdown_script.append(mdline)
    mdline = ("")
    markdown_script.append(mdline)
    mdline = ("## License Keys")
    markdown_script.append(mdline)
    mdline = ("| Parameter | Configured Value |")
    markdown_script.append(mdline)
    mdline = ("|-----------|------------------|")
    markdown_script.append(mdline)
    mdline = ("| ESXi License Key |  |")
    markdown_script.append(mdline)
    mdline = ("| vCenter License Key |  |")
    markdown_script.append(mdline)
    mdline = ("| vSAN License Key |  |")
    markdown_script.append(mdline)
    mdline = ("| NSX License Key |  |")
    markdown_script.append(mdline)
    mdline = ("")
    markdown_script.append(mdline)
    mdline = ("## Credentials")
    markdown_script.append(mdline)
    mdline = ("| Parameter | Configured Value |")
    markdown_script.append(mdline)
    mdline = ("|-----------|------------------|")
    markdown_script.append(mdline)
    mdline = ("| SDDC Manager Local User Password |  |")
    markdown_script.append(mdline)
    mdline = ("| SDDC Manager Root User Username |  |")
    markdown_script.append(mdline)
    mdline = ("| SDDC Manager Root User Password |  |")
    markdown_script.append(mdline)
    mdline = ("| SDDC Manager Second User Username |  |")
    markdown_script.append(mdline)
    mdline = ("| SDDC Manager Second User Password |  |")
    markdown_script.append(mdline)
    mdline = ("| root NSX Manager Password |  |")
    markdown_script.append(mdline)
    mdline = ("| NSX Admin Password |  |")
    markdown_script.append(mdline)
    mdline = ("| NSX Audit Password |  |")
    markdown_script.append(mdline)
    mdline = ("| Platform Services Controller Admin User SSO Password |  |")
    markdown_script.append(mdline)
    mdline = ("| vCenter Root Password |  |")
    markdown_script.append(mdline)
    mdline = ("| ESXi Host 1 Username |  |  |")
    markdown_script.append(mdline)
    mdline = ("| ESXi Host 1 Password |  |  |")
    markdown_script.append(mdline)
    mdline = ("| ESXi Host 2 Username |  |  |")
    markdown_script.append(mdline)
    mdline = ("| ESXi Host 2 Password |  |  |")
    markdown_script.append(mdline)
    mdline = ("| ESXi Host 3 Username |  |  |")
    markdown_script.append(mdline)
    mdline = ("| ESXi Host 3 Password |  |  |")
    markdown_script.append(mdline)
    mdline = ("| ESXi Host 4 Username |  |  |")
    markdown_script.append(mdline)
    mdline = ("| ESXi Host 4 Password |  |  |")
    markdown_script.append(mdline)
    mdline = ("")
    markdown_script.append(mdline)
    mdline = ("## Network Specs")
    markdown_script.append(mdline)
    mdline = ("| Parameter | Configured Value |")
    markdown_script.append(mdline)
    mdline = ("|-----------|------------------|")
    markdown_script.append(mdline)
    mdline = ("| Management Subnet |  |")
    markdown_script.append(mdline)
    mdline = ("| Management VLAN ID |  |")
    markdown_script.append(mdline)
    mdline = ("| Management MTU |  |")
    markdown_script.append(mdline)
    mdline = ("| Management Gateway |  |")
    markdown_script.append(mdline)
    mdline = ("|  |  |")
    markdown_script.append(mdline)
    mdline = ("| VSAN Subnet |  |")
    markdown_script.append(mdline)
    mdline = ("| VSAN VLAN ID |  |")
    markdown_script.append(mdline)
    mdline = ("| VSAN MTU |  |")
    markdown_script.append(mdline)
    mdline = ("| VSAN Gateway |  |")
    markdown_script.append(mdline)
    mdline = ("| VSAN Included IP Addresses |  |")
    markdown_script.append(mdline)
    mdline = ("|  |  |")
    markdown_script.append(mdline)
    mdline = ("| VMOTION Subnet |  |")
    markdown_script.append(mdline)
    mdline = ("| VMOTION VLAN ID |  |")
    markdown_script.append(mdline)
    mdline = ("| VMOTION MTU |  |")
    markdown_script.append(mdline)
    mdline = ("| VMOTION Gateway |  |")
    markdown_script.append(mdline)
    mdline = ("| VMOTION Included IP Address Ranges |  |")
    markdown_script.append(mdline)
    mdline = ("|  |  |")
    markdown_script.append(mdline)
    mdline = ("| TEP Subnet (CIDR) |  |")
    markdown_script.append(mdline)
    mdline = ("| TEP VLAN ID |  |")
    markdown_script.append(mdline)
    mdline = ("| TEP MTU |  |")
    markdown_script.append(mdline)
    mdline = ("| TEP Gateway |  |")
    markdown_script.append(mdline)
    mdline = ("| IP Address Pool Ranges |")
    markdown_script.append(mdline)
    mdline = ("")
    markdown_script.append(mdline)
    mdline = ("## Domain Specs")
    markdown_script.append(mdline)
    mdline = ("| Parameter | Configured Value |")
    markdown_script.append(mdline)
    mdline = ("|-----------|------------------|")
    markdown_script.append(mdline)
    mdline = ("| NTP Servers |  |")
    markdown_script.append(mdline)
    mdline = ("| Subdomain |  |")
    markdown_script.append(mdline)
    mdline = ("| Domain |  |")
    markdown_script.append(mdline)
    mdline = ("| Name Server |  |")
    markdown_script.append(mdline)
    mdline = ("| Secondary Name Server |  |")
    markdown_script.append(mdline)
    mdline = ("")
    markdown_script.append(mdline)
    mdline = ("## DNS Entries")
    markdown_script.append(mdline)
    mdline = ("| Parameter | Hostname | IP Address |")
    markdown_script.append(mdline)
    mdline = ("|-----------|----------|------------|")
    markdown_script.append(mdline)
    mdline = ("| SDDC Manager |  |  |")
    markdown_script.append(mdline)
    mdline = ("| NSX Manager A |  |  |")
    markdown_script.append(mdline)
    mdline = ("| NSX Manager B |  |  |")
    markdown_script.append(mdline)
    mdline = ("| NSX Manager C |  |  |")
    markdown_script.append(mdline)
    mdline = ("| NSX Manager VIP |  |  |")
    markdown_script.append(mdline)
    mdline = ("| vCenter |  |  |")
    markdown_script.append(mdline)
    mdline = ("| ESXi Host 1 |  |  |")
    markdown_script.append(mdline)
    mdline = ("| ESXi Host 2 |  |  |")
    markdown_script.append(mdline)
    mdline = ("| ESXi Host 3 |  |  |")
    markdown_script.append(mdline)
    mdline = ("| ESXi Host 4 |  |  |")
    markdown_script.append(mdline)
    mdline = ("")
    markdown_script.append(mdline)
    mdline = ("## NSXT Specs")
    markdown_script.append(mdline)
    mdline = ("| Parameter | Configured Value |")
    markdown_script.append(mdline)
    mdline = ("|-----------|------------------|")
    markdown_script.append(mdline)
    mdline = ("| NSX Manager Size |  |")
    markdown_script.append(mdline)
    mdline = ("| Overlay Transport Zone Name |  |")
    markdown_script.append(mdline)
    mdline = ("| Overlay Transport Network Name |  |")
    markdown_script.append(mdline)
    mdline = ("| VLAN Transport Zone Name |  |")
    markdown_script.append(mdline)
    mdline = ("| VLAN Transport Network Name |  |")
    markdown_script.append(mdline)
    mdline = ("")
    markdown_script.append(mdline)
    mdline = ("## SDDC Manager Specs")
    markdown_script.append(mdline)
    mdline = ("| Parameter | Configured Value |")
    markdown_script.append(mdline)
    mdline = ("|-----------|------------------|")
    markdown_script.append(mdline)
    mdline = ("| Netmask   |  |")
    markdown_script.append(mdline)
    mdline = ("")
    markdown_script.append(mdline)
    mdline = ("## VSAN Specs")
    markdown_script.append(mdline)
    mdline = ("| Parameter | Configured Value |")
    markdown_script.append(mdline)
    mdline = ("|-----------|------------------|")
    markdown_script.append(mdline)
    mdline = ("| vSAN Name |  |")
    markdown_script.append(mdline)
    mdline = ("| Datastore Name |  |")
    markdown_script.append(mdline)
    mdline = ("")
    markdown_script.append(mdline)
    mdline = ("## Distributed Virtual Switch Specs")
    markdown_script.append(mdline)
    mdline = ("| Parameter | Configured Value |")
    markdown_script.append(mdline)
    mdline = ("|-----------|------------------|")
    markdown_script.append(mdline)
    mdline = ("| MTU |  |")
    markdown_script.append(mdline)
    mdline = ("| VSAN Traffic Type |  |")
    markdown_script.append(mdline)
    mdline = ("| VMOTION Traffic Type |  |")
    markdown_script.append(mdline)
    mdline = ("| VDP Traffic Type |  |")
    markdown_script.append(mdline)
    mdline = ("| VIRTUALMACHINE Traffic Type |  |")
    markdown_script.append(mdline)
    mdline = ("| MANAGEMENT Traffic Type |  |")
    markdown_script.append(mdline)
    mdline = ("| NFS Traffic Type |  |")
    markdown_script.append(mdline)
    mdline = ("| HBR Traffic Type |  |")
    markdown_script.append(mdline)
    mdline = ("| FAULTTOLERANCE Traffic Type |  |")
    markdown_script.append(mdline)
    mdline = ("| ISCSI Traffic Type |  |")
    markdown_script.append(mdline)
    mdline = ("| DVS Name |  |")
    markdown_script.append(mdline)
    mdline = ("| vmnics |  |")
    markdown_script.append(mdline)
    mdline = ("| Networks |  |")
    markdown_script.append(mdline)
    mdline = ("")
    markdown_script.append(mdline)
    mdline = ("## ESXi Cluster Specs")
    markdown_script.append(mdline)
    mdline = ("| Parameter | Configured Value |")
    markdown_script.append(mdline)
    mdline = ("|-----------|------------------|")
    markdown_script.append(mdline)
    mdline = ("| Cluster Name |  |")
    markdown_script.append(mdline)
    mdline = ("| Cluster EVC Mode |  |")
    markdown_script.append(mdline)
    # Loop through these
    mdline = ("| Resource Pool Specs: |  |")
    markdown_script.append(mdline)
    mdline = ("| Name |  |")
    markdown_script.append(mdline)
    mdline = ("| Type |  |")
    markdown_script.append(mdline)
    mdline = ("| CPU Shares Level |  |")
    markdown_script.append(mdline)
    mdline = ("| CPU Shares Value |  |")
    markdown_script.append(mdline)
    mdline = ("| CPU Limit |  |")
    markdown_script.append(mdline)
    mdline = ("| CPU Reservation Percentage |  |")
    markdown_script.append(mdline)
    mdline = ("| CPU Reservation Expandable |  |")
    markdown_script.append(mdline)
    mdline = ("| Memory Shares Level |  |")
    markdown_script.append(mdline)
    mdline = ("| Memory Shares Value |  |")
    markdown_script.append(mdline)
    mdline = ("| Memory Limit |  |")
    markdown_script.append(mdline)
    mdline = ("| Memery Reservation Percentage |  |")
    markdown_script.append(mdline)
    mdline = ("| Memory Reservation Expandable |  |")
    markdown_script.append(mdline)
    # End loop
    mdline = ("")
    markdown_script.append(mdline)
    mdline = ("## Platform Services Controller Specs")
    markdown_script.append(mdline)
    mdline = ("| Parameter | Configured Value |")
    markdown_script.append(mdline)
    mdline = ("|-----------|------------------|")
    markdown_script.append(mdline)
    mdline = ("| PSC ID |  |")
    markdown_script.append(mdline)
    mdline = ("| SSO Domain |  |")
    markdown_script.append(mdline)
    mdline = ("")
    markdown_script.append(mdline)
    mdline = ("## vCenter Spec")
    markdown_script.append(mdline)
    mdline = ("| Parameter | Configured Value |")
    markdown_script.append(mdline)
    mdline = ("|-----------|------------------|")
    markdown_script.append(mdline)
    mdline = ("| VM Size |  |")
    markdown_script.append(mdline)
    mdline = ("")
    markdown_script.append(mdline)
    # Loop through these
    mdline = ("## ESXi Host Specs")
    markdown_script.append(mdline)
    mdline = ("| Server ID | Hostname | Association | vSwitch | Subnet Mask | CIDR | Gateway | IP Address |")
    markdown_script.append(mdline)
    mdline = ("|-----------|----------|-------------|---------|-------------|------|---------|------------|")
    markdown_script.append(mdline)
    mdline = ("|  |  |  |  |  |  |  |  |")
    markdown_script.append(mdline)
    return markdown_script